### ISSUE TITLE
CohortExplorer shiny app fails on any computer that is not Gowtham's

### ISSUE THREAD

**Issue by schuemie** [OHDSI/StudyDiagnostics#618]
There is an awful lot of code in [global.R](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/CohortExplorer/global.R) that refers to global variables set in Gowtham's environment (like `cdmSources`, but also credentials in keyring). None of that code should be there, even if it would gracefully handle not being Gowtham (which it doesn't). If you want to use your own credentials, please do so when calling `launchCohortExplorer()`, so outside the package.  

As a results, the code actually doesn't work. If you're not Gowtham. I get 
```
Error in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Element not found.
```

**Comment by azimov** [comment]
The user code that caused this issue has been merged in to the develop branch
